back_end:
    resource: "@BackEndBundle/Resources/config/routing.yml"
    prefix:   /backend

front_end:
    resource: "@FrontEndBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"