back_end:
    resource: "@BackEndBundle/Resources/config/routing.yml"
    prefix:   /backend

front_end:
    resource: "@FrontEndBundle/Resources/config/routing.yml"
    prefix:   /frontend

app:
    resource: '@AppBundle/Controller/'
    type: annotation
# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#comment bundle
fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }  
#forum
discutea_forum:
    resource: "@DForumBundle/Resources/config/routing.yml"
    prefix:   /      
#chat
belousovr:
     resource: "@belousovChatBundle/Controller"
     type:     annotation    