back_end:
    resource: "@BackEndBundle/Resources/config/routing.yml"
    prefix:   /backend

front_end:
    resource: "@FrontEndBundle/Resources/config/routing.yml"
    prefix:   /frontend

app:
    resource: '@AppBundle/Controller/'
    type: annotation
