# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value
    belousov.chat.user_class: BackEndBundle\Entity\User
services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    belousov.mapping.listener:
        class: belousovr\belousovChatBundle\EventListener\DynamicRelationSubscriber
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata }
        arguments:
            - %belousov.chat.user_class% 