<?php

namespace BackEndBundle\Repository;

/**
 * catfamiliaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class catfamiliaRepository extends \Doctrine\ORM\EntityRepository
{
}
