<?php

namespace BackEndBundle\Repository;

/**
 * catgramaticalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class catgramaticalRepository extends \Doctrine\ORM\EntityRepository
{
}
