<?php

namespace BackEndBundle\Repository;

/**
 * contacteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class contacteRepository extends \Doctrine\ORM\EntityRepository
{
}
