<?php

namespace BackEndBundle\Repository;

/**
 * idiomaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class idiomaRepository extends \Doctrine\ORM\EntityRepository
{
}
