<?php

namespace BackEndBundle\Repository;

/**
 * logRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class logRepository extends \Doctrine\ORM\EntityRepository
{
}
