<?php

namespace BackEndBundle\Repository;

/**
 * missatgeriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class missatgeriaRepository extends \Doctrine\ORM\EntityRepository
{
}
