<?php

namespace BackEndBundle\Repository;

/**
 * ParaulaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParaulaRepository extends \Doctrine\ORM\EntityRepository
{
}
