<?php

namespace BackEndBundle\Repository;

/**
 * textatraduirRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class textatraduirRepository extends \Doctrine\ORM\EntityRepository
{
}
