<?php

namespace BackEndBundle\Repository;

/**
 * texttraduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class texttraduitRepository extends \Doctrine\ORM\EntityRepository
{
}
