<?php

namespace BackEndBundle\Repository;

/**
 * traduccioparaulaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class traduccioparaulaRepository extends \Doctrine\ORM\EntityRepository
{
}
