<?php

namespace BackEndBundle\Repository;

/**
 * usuariRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class usuariRepository extends \Doctrine\ORM\EntityRepository
{
}
