<?php

namespace BackEndBundle\Repository;

/**
 * valoracioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class valoracioRepository extends \Doctrine\ORM\EntityRepository
{
}
