exchangeit_back_end_homepage:
    path:     /
    defaults: { _controller: BackEndBundle:Default:index }

#USUARI
exchangeit_back_end_usuari_edit:
    path:     /edit/{id}
    defaults: { _controller: FOSUserBundle:Profile:edit }

exchangeit_back_end_usuari_delete:
    path:     /delete/{id}
    defaults: { _controller: BackEndBundle:Default:delete }

#LLISTATS
exchangeit_back_end_llistaCatGramatical:
    path:     /llistaCatGramatical
    defaults: { _controller: BackEndBundle:Default:llistaCatGramatical }

exchangeit_back_end_llistaCatFamilia:
    path:     /llistaCatFamilia
    defaults: { _controller: BackEndBundle:Default:llistaCatFamilia }

exchangeit_back_end_llistaUsuaris:
    path:     /llistaUsuaris
    defaults: { _controller: BackEndBundle:Default:llistaUsuaris }

exchangeit_back_end_llistaIdiomes:
    path:     /llistaIdioma
    defaults: { _controller: BackEndBundle:Default:llistaIdioma }